### ISSUE TITLE
Missing OpenStreetMap attribution

### ISSUE THREAD

**Issue by mmd-osm** [mwarhaftig/CoinTravelerServer#1]
Hi there,

I noticed you're using OpenStreetMap data via Overpass API. However, your screenshots / website / apps seem to lack proper attribution for OSM. Can you please fix this?

See https://www.openstreetmap.org/copyright for details.

Thanks!

@simonpoole

**Comment by mwarhaftig** [comment]
Hi Simon, 

Check out [README.md](https://github.com/mwarhaftig/CoinTravelerServer/blob/master/README.md) for the updates to include attribution.

**Comment by mmd-osm** [comment]
great, thanks! Closing issue now.
